package com.hgsoft.carowner.entity;
// Generated 2015-8-28 14:58:55 by Hibernate Tools 3.4.0.CR1

/**
 * CarDispatch generated by hbm2java
 */
public class CarDispatch implements java.io.Serializable {

	private String id;
	private String obdSn;
	private String carId;
	private String userName;
	private String mobileNumber;
	private String drivingOutAddress;
	private String drivingOutTime;
	private String offRunningAddress;
	private String offRunningTime;
	private String destination;
	private String status;
	private String comment;

	public CarDispatch() {
	}

	public CarDispatch(String id) {
		this.id = id;
	}

	public CarDispatch(String id, String obdSn, String carId, String userName,
			String mobileNumber, String drivingOutAddress,
			String drivingOutTime, String offRunningAddress,
			String offRunningTime, String destination, String status,
			String comment) {
		this.id = id;
		this.obdSn = obdSn;
		this.carId = carId;
		this.userName = userName;
		this.mobileNumber = mobileNumber;
		this.drivingOutAddress = drivingOutAddress;
		this.drivingOutTime = drivingOutTime;
		this.offRunningAddress = offRunningAddress;
		this.offRunningTime = offRunningTime;
		this.destination = destination;
		this.status = status;
		this.comment = comment;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getObdSn() {
		return this.obdSn;
	}

	public void setObdSn(String obdSn) {
		this.obdSn = obdSn;
	}

	public String getCarId() {
		return this.carId;
	}

	public void setCarId(String carId) {
		this.carId = carId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	public String getDrivingOutAddress() {
		return this.drivingOutAddress;
	}

	public void setDrivingOutAddress(String drivingOutAddress) {
		this.drivingOutAddress = drivingOutAddress;
	}

	public String getDrivingOutTime() {
		return this.drivingOutTime;
	}

	public void setDrivingOutTime(String drivingOutTime) {
		this.drivingOutTime = drivingOutTime;
	}

	public String getOffRunningAddress() {
		return this.offRunningAddress;
	}

	public void setOffRunningAddress(String offRunningAddress) {
		this.offRunningAddress = offRunningAddress;
	}

	public String getOffRunningTime() {
		return this.offRunningTime;
	}

	public void setOffRunningTime(String offRunningTime) {
		this.offRunningTime = offRunningTime;
	}

	public String getDestination() {
		return this.destination;
	}

	public void setDestination(String destination) {
		this.destination = destination;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
