package com.hgsoft.carowner.entity;
// Generated 2015-7-29 17:16:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CarInfo generated by hbm2java
 */
public class CarInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3757905273024071178L;
	private String carId;//车辆编号
	private String obdSn;//智能盒激活码（SN码）
	private String regUserId;//智能盒激活码（SN码）
	private String license;//车牌号
	private String carState;//车辆状态	 00 未设置防盗状态 	01 已设置防盗状态
	private String cartypeId;//车型信息
	private Integer isfault;//默认值：0，是否发生故障，0：无故障， 1：故障
	private Date createTime;//创建时间
	private Date updateTime;//更新时间
	private String valid;//是否有效，1有效0无效
	
	public CarInfo() {
	}

	public CarInfo(String carId, String obdSn) {
		this.carId = carId;
		this.obdSn = obdSn;
	}

	public CarInfo(String carId, String obdSn, String license, String carState,
			String cartypeId) {
		this.carId = carId;
		this.obdSn = obdSn;
		this.license = license;
		this.carState = carState;
		this.cartypeId = cartypeId;
	}

	public String getCarId() {
		return this.carId;
	}

	public void setCarId(String carId) {
		this.carId = carId;
	}

	public String getObdSn() {
		return this.obdSn;
	}

	public void setObdSn(String obdSn) {
		this.obdSn = obdSn;
	}

	public String getLicense() {
		return this.license;
	}

	public void setLicense(String license) {
		this.license = license;
	}

	public String getCarState() {
		return this.carState;
	}

	public void setCarState(String carState) {
		this.carState = carState;
	}

	public String getCartypeId() {
		return this.cartypeId;
	}

	public void setCartypeId(String cartypeId) {
		this.cartypeId = cartypeId;
	}

	public Integer getIsfault() {
		return isfault;
	}

	public void setIsfault(Integer isfault) {
		this.isfault = isfault;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getValid() {
		return valid;
	}

	public void setValid(String valid) {
		this.valid = valid;
	}

	public String getRegUserId() {
		return regUserId;
	}

	public void setRegUserId(String regUserId) {
		this.regUserId = regUserId;
	}

}
