package com.hgsoft.carowner.entity;
// Generated 2015-8-31 14:09:53 by Hibernate Tools 3.4.0.CR1

/**
 * CarMaintain generated by hbm2java
 */
public class CarMaintain implements java.io.Serializable {

	private String id;
	private String obdSn;
	private String carId;
	private String maintainStatus;
	private String orderStatus;
	private String maintainTime;

	public CarMaintain() {
	}

	public CarMaintain(String id) {
		this.id = id;
	}

	public CarMaintain(String id, String obdSn, String carId,
			String maintainStatus, String orderStatus, String maintainTime) {
		this.id = id;
		this.obdSn = obdSn;
		this.carId = carId;
		this.maintainStatus = maintainStatus;
		this.orderStatus = orderStatus;
		this.maintainTime = maintainTime;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getObdSn() {
		return this.obdSn;
	}

	public void setObdSn(String obdSn) {
		this.obdSn = obdSn;
	}

	public String getCarId() {
		return this.carId;
	}

	public void setCarId(String carId) {
		this.carId = carId;
	}

	public String getMaintainStatus() {
		return this.maintainStatus;
	}

	public void setMaintainStatus(String maintainStatus) {
		this.maintainStatus = maintainStatus;
	}

	public String getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	public String getMaintainTime() {
		return this.maintainTime;
	}

	public void setMaintainTime(String maintainTime) {
		this.maintainTime = maintainTime;
	}

}
