package com.hgsoft.carowner.entity;

// Generated 2015-8-28 11:24:12 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * CarParam generated by hbm2java
 */
public class CarParam implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String obdSn;
	private String areaNum;
	private String railAndAlert;
	private String maxLongitude;
	private String maxLatitude;
	private String minLongitude;
	private String minLatitude;
	private String overspeed;
	private String sleepTime;
	private String accTime;
	private String heartTime;
	private String gps;
	private String position;
	private String safety;
	private String timeZone;
	private String voltage;
	private String gsm;
	private String undervoltage;
	private String highVoltage;
	private String tiredDrive;
	private String tiredDriveTime;
	private String waterTemp;
	private String userId;
	private String ebrake;
	private String espeedup;
	private String crash;
	private String shake;
	private String speedRemind;
	private String imei;
	private String dataUploadTime;
	private String dataUploadType;
	private String positionExtra;
	private String gsmbts;
	private String communication;
	private String positionType;
	private Date createTime;
	private Character valid;
	private String remark;

	public CarParam() {
	}

	public CarParam(String obdSn, String areaNum, String railAndAlert,
			String maxLongitude, String maxLatitude, String minLongitude,
			String minLatitude, String overspeed, String sleepTime,
			String accTime, String heartTime, String gps, String position,
			String safety, String timeZone, String voltage, String gsm,
			String undervoltage, String highVoltage, String tiredDrive,
			String tiredDriveTime, String waterTemp, String userId,
			String ebrake, String espeedup, String crash, String shake,
			String speedRemind, String imei, String dataUploadTime,
			String dataUploadType, String positionExtra, String gsmbts,
			String communication, String positionType, String ip, String port,
			String apn, Date createTime, Character valid, String remark) {
		this.obdSn = obdSn;
		this.areaNum = areaNum;
		this.railAndAlert = railAndAlert;
		this.maxLongitude = maxLongitude;
		this.maxLatitude = maxLatitude;
		this.minLongitude = minLongitude;
		this.minLatitude = minLatitude;
		this.overspeed = overspeed;
		this.sleepTime = sleepTime;
		this.accTime = accTime;
		this.heartTime = heartTime;
		this.gps = gps;
		this.position = position;
		this.safety = safety;
		this.timeZone = timeZone;
		this.voltage = voltage;
		this.gsm = gsm;
		this.undervoltage = undervoltage;
		this.highVoltage = highVoltage;
		this.tiredDrive = tiredDrive;
		this.tiredDriveTime = tiredDriveTime;
		this.waterTemp = waterTemp;
		this.userId = userId;
		this.ebrake = ebrake;
		this.espeedup = espeedup;
		this.crash = crash;
		this.shake = shake;
		this.speedRemind = speedRemind;
		this.imei = imei;
		this.dataUploadTime = dataUploadTime;
		this.dataUploadType = dataUploadType;
		this.positionExtra = positionExtra;
		this.gsmbts = gsmbts;
		this.communication = communication;
		this.positionType = positionType;
		this.createTime = createTime;
		this.valid = valid;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getObdSn() {
		return this.obdSn;
	}

	public void setObdSn(String obdSn) {
		this.obdSn = obdSn;
	}

	public String getAreaNum() {
		return this.areaNum;
	}

	public void setAreaNum(String areaNum) {
		this.areaNum = areaNum;
	}

	public String getRailAndAlert() {
		return this.railAndAlert;
	}

	public void setRailAndAlert(String railAndAlert) {
		this.railAndAlert = railAndAlert;
	}

	public String getMaxLongitude() {
		return this.maxLongitude;
	}

	public void setMaxLongitude(String maxLongitude) {
		this.maxLongitude = maxLongitude;
	}

	public String getMaxLatitude() {
		return this.maxLatitude;
	}

	public void setMaxLatitude(String maxLatitude) {
		this.maxLatitude = maxLatitude;
	}

	public String getMinLongitude() {
		return this.minLongitude;
	}

	public void setMinLongitude(String minLongitude) {
		this.minLongitude = minLongitude;
	}

	public String getMinLatitude() {
		return this.minLatitude;
	}

	public void setMinLatitude(String minLatitude) {
		this.minLatitude = minLatitude;
	}

	public String getOverspeed() {
		return this.overspeed;
	}

	public void setOverspeed(String overspeed) {
		this.overspeed = overspeed;
	}

	public String getSleepTime() {
		return this.sleepTime;
	}

	public void setSleepTime(String sleepTime) {
		this.sleepTime = sleepTime;
	}

	public String getAccTime() {
		return this.accTime;
	}

	public void setAccTime(String accTime) {
		this.accTime = accTime;
	}

	public String getHeartTime() {
		return this.heartTime;
	}

	public void setHeartTime(String heartTime) {
		this.heartTime = heartTime;
	}

	public String getGps() {
		return this.gps;
	}

	public void setGps(String gps) {
		this.gps = gps;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public String getSafety() {
		return this.safety;
	}

	public void setSafety(String safety) {
		this.safety = safety;
	}

	public String getTimeZone() {
		return this.timeZone;
	}

	public void setTimeZone(String timeZone) {
		this.timeZone = timeZone;
	}

	public String getVoltage() {
		return this.voltage;
	}

	public void setVoltage(String voltage) {
		this.voltage = voltage;
	}

	public String getGsm() {
		return this.gsm;
	}

	public void setGsm(String gsm) {
		this.gsm = gsm;
	}

	public String getUndervoltage() {
		return this.undervoltage;
	}

	public void setUndervoltage(String undervoltage) {
		this.undervoltage = undervoltage;
	}

	public String getHighVoltage() {
		return this.highVoltage;
	}

	public void setHighVoltage(String highVoltage) {
		this.highVoltage = highVoltage;
	}

	public String getTiredDrive() {
		return this.tiredDrive;
	}

	public void setTiredDrive(String tiredDrive) {
		this.tiredDrive = tiredDrive;
	}

	public String getTiredDriveTime() {
		return this.tiredDriveTime;
	}

	public void setTiredDriveTime(String tiredDriveTime) {
		this.tiredDriveTime = tiredDriveTime;
	}

	public String getWaterTemp() {
		return this.waterTemp;
	}

	public void setWaterTemp(String waterTemp) {
		this.waterTemp = waterTemp;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getEbrake() {
		return this.ebrake;
	}

	public void setEbrake(String ebrake) {
		this.ebrake = ebrake;
	}

	public String getEspeedup() {
		return this.espeedup;
	}

	public void setEspeedup(String espeedup) {
		this.espeedup = espeedup;
	}

	public String getCrash() {
		return this.crash;
	}

	public void setCrash(String crash) {
		this.crash = crash;
	}

	public String getShake() {
		return this.shake;
	}

	public void setShake(String shake) {
		this.shake = shake;
	}

	public String getSpeedRemind() {
		return this.speedRemind;
	}

	public void setSpeedRemind(String speedRemind) {
		this.speedRemind = speedRemind;
	}

	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	public String getDataUploadTime() {
		return this.dataUploadTime;
	}

	public void setDataUploadTime(String dataUploadTime) {
		this.dataUploadTime = dataUploadTime;
	}

	public String getDataUploadType() {
		return this.dataUploadType;
	}

	public void setDataUploadType(String dataUploadType) {
		this.dataUploadType = dataUploadType;
	}

	public String getPositionExtra() {
		return this.positionExtra;
	}

	public void setPositionExtra(String positionExtra) {
		this.positionExtra = positionExtra;
	}

	public String getGsmbts() {
		return this.gsmbts;
	}

	public void setGsmbts(String gsmbts) {
		this.gsmbts = gsmbts;
	}

	public String getCommunication() {
		return this.communication;
	}

	public void setCommunication(String communication) {
		this.communication = communication;
	}

	public String getPositionType() {
		return this.positionType;
	}

	public void setPositionType(String positionType) {
		this.positionType = positionType;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Character getValid() {
		return this.valid;
	}

	public void setValid(Character valid) {
		this.valid = valid;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
