package com.hgsoft.carowner.entity;
// Generated 2015-8-31 14:09:53 by Hibernate Tools 3.4.0.CR1

/**
 * CarTraffic generated by hbm2java
 */
public class CarTraffic implements java.io.Serializable {

	private String id;
	private String obdSn;
	private String carId;
	private String trafficStatus;
	private String trafficTime;

	public CarTraffic() {
	}

	public CarTraffic(String id) {
		this.id = id;
	}

	public CarTraffic(String id, String obdSn, String carId,
			String trafficStatus, String trafficTime) {
		this.id = id;
		this.obdSn = obdSn;
		this.carId = carId;
		this.trafficStatus = trafficStatus;
		this.trafficTime = trafficTime;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getObdSn() {
		return this.obdSn;
	}

	public void setObdSn(String obdSn) {
		this.obdSn = obdSn;
	}

	public String getCarId() {
		return this.carId;
	}

	public void setCarId(String carId) {
		this.carId = carId;
	}

	public String getTrafficStatus() {
		return this.trafficStatus;
	}

	public void setTrafficStatus(String trafficStatus) {
		this.trafficStatus = trafficStatus;
	}

	public String getTrafficTime() {
		return this.trafficTime;
	}

	public void setTrafficTime(String trafficTime) {
		this.trafficTime = trafficTime;
	}

}
