package com.hgsoft.carowner.entity;
// Generated 2015-8-31 14:09:53 by Hibernate Tools 3.4.0.CR1

/**
 * CarViolation generated by hbm2java
 */
public class CarViolation implements java.io.Serializable {

	private String id;
	private String obdSn;
	private String carId;
	private String violationTime;
	private String violationAddress;
	private String violationDesc;
	private String penaltyPoints;
	private String principal;
	private String overdueFine;
	private String commission;
	private String comment;

	public CarViolation() {
	}

	public CarViolation(String id) {
		this.id = id;
	}

	public CarViolation(String id, String obdSn, String carId,
			String violationTime, String violationAddress,
			String violationDesc, String penaltyPoints, String principal,
			String overdueFine, String commission, String comment) {
		this.id = id;
		this.obdSn = obdSn;
		this.carId = carId;
		this.violationTime = violationTime;
		this.violationAddress = violationAddress;
		this.violationDesc = violationDesc;
		this.penaltyPoints = penaltyPoints;
		this.principal = principal;
		this.overdueFine = overdueFine;
		this.commission = commission;
		this.comment = comment;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getObdSn() {
		return this.obdSn;
	}

	public void setObdSn(String obdSn) {
		this.obdSn = obdSn;
	}

	public String getCarId() {
		return this.carId;
	}

	public void setCarId(String carId) {
		this.carId = carId;
	}

	public String getViolationTime() {
		return this.violationTime;
	}

	public void setViolationTime(String violationTime) {
		this.violationTime = violationTime;
	}

	public String getViolationAddress() {
		return this.violationAddress;
	}

	public void setViolationAddress(String violationAddress) {
		this.violationAddress = violationAddress;
	}

	public String getViolationDesc() {
		return this.violationDesc;
	}

	public void setViolationDesc(String violationDesc) {
		this.violationDesc = violationDesc;
	}

	public String getPenaltyPoints() {
		return this.penaltyPoints;
	}

	public void setPenaltyPoints(String penaltyPoints) {
		this.penaltyPoints = penaltyPoints;
	}

	public String getPrincipal() {
		return this.principal;
	}

	public void setPrincipal(String principal) {
		this.principal = principal;
	}

	public String getOverdueFine() {
		return this.overdueFine;
	}

	public void setOverdueFine(String overdueFine) {
		this.overdueFine = overdueFine;
	}

	public String getCommission() {
		return this.commission;
	}

	public void setCommission(String commission) {
		this.commission = commission;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
