package com.hgsoft.carowner.entity;

// Generated 2015-7-30 12:44:37 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Dictionary generated by hbm2java
 */
public class Dictionary implements java.io.Serializable {

	private String id;
	private String code;
	private String trueValue;
	private String showValue;
	private String type;
	private Date createTime;
	private String createUser;
	private String state;
	private String remark;

	public Dictionary() {
	}

	public Dictionary(String id) {
		this.id = id;
	}

	public Dictionary(String id, String code, String trueValue,
			String showValue, String type, Date createTime, String createUser,
			String state, String remark) {
		this.id = id;
		this.code = code;
		this.trueValue = trueValue;
		this.showValue = showValue;
		this.type = type;
		this.createTime = createTime;
		this.createUser = createUser;
		this.state = state;
		this.remark = remark;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getTrueValue() {
		return this.trueValue;
	}

	public void setTrueValue(String trueValue) {
		this.trueValue = trueValue;
	}

	public String getShowValue() {
		return this.showValue;
	}

	public void setShowValue(String showValue) {
		this.showValue = showValue;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
