package com.hgsoft.carowner.entity;

import java.util.Date;

/**
 * Wifi generated by hbm2java
 */
public class DomainState implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	private String obdSn;
	
	private String whiteSwitch;
	private String blackSwitch;
	private String whiteList;
	private String blackList;
	
	private Date createTime;
	private Date updateTime;
	private Integer valid;

	public DomainState() {
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getObdSn() {
		return obdSn;
	}

	public void setObdSn(String obdSn) {
		this.obdSn = obdSn;
	}

	
	public String getWhiteSwitch() {
		return whiteSwitch;
	}

	public void setWhiteSwitch(String whiteSwitch) {
		this.whiteSwitch = whiteSwitch;
	}

	public String getBlackSwitch() {
		return blackSwitch;
	}

	public void setBlackSwitch(String blackSwitch) {
		this.blackSwitch = blackSwitch;
	}

	public String getWhiteList() {
		return whiteList;
	}

	public void setWhiteList(String whiteList) {
		this.whiteList = whiteList;
	}

	public String getBlackList() {
		return blackList;
	}

	public void setBlackList(String blackList) {
		this.blackList = blackList;
	}

	public Integer getValid() {
		return valid;
	}

	public void setValid(Integer valid) {
		this.valid = valid;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Override
	public String toString() {
		return "DomainState [id=" + id + ", obdSn=" + obdSn + ", whiteSwitch=" + whiteSwitch + ", blackSwitch="
				+ blackSwitch + ", whiteList=" + whiteList + ", blackList=" + blackList + ", createTime=" + createTime
				+ ", updateTime=" + updateTime + ", valid=" + valid + "]";
	}
	
}
