package com.hgsoft.carowner.entity;
// Generated 2015-7-29 17:16:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CarInfo generated by hbm2java
 */
public class Efence implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Integer id;
	private String obdSn;
	private String type;
	private String railAndAlert;
	private String areaNum;
	private String maxLongitude;
	private String maxLatitude;
	private String minLongitude;
	private String minLatitude;
	private Date startDate;
	private Date endDate;
	private String isChange;
	private Date createTime;//创建时间
	private Date updateTime;//更新时间
	private String valid;//是否有效，1有效0无效
	
	public Efence() {
	}

	

	@Override
	public String toString() {
		return "Efence [id=" + id + ", obdSn=" + obdSn + ", type=" + type + ", railAndAlert=" + railAndAlert
				+ ", areaNum=" + areaNum + ", maxLongitude=" + maxLongitude + ", maxLatitude=" + maxLatitude
				+ ", minLongitude=" + minLongitude + ", minLatitude=" + minLatitude + ", startDate=" + startDate
				+ ", endDate=" + endDate + ", isChange=" + isChange + ", createTime=" + createTime + ", updateTime="
				+ updateTime + ", valid=" + valid + "]";
	}



	public String getIsChange() {
		return isChange;
	}

	public void setIsChange(String isChange) {
		this.isChange = isChange;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getObdSn() {
		return obdSn;
	}

	public void setObdSn(String obdSn) {
		this.obdSn = obdSn;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getRailAndAlert() {
		return railAndAlert;
	}

	public void setRailAndAlert(String railAndAlert) {
		this.railAndAlert = railAndAlert;
	}

	public String getAreaNum() {
		return areaNum;
	}

	public void setAreaNum(String areaNum) {
		this.areaNum = areaNum;
	}

	public String getMaxLongitude() {
		return maxLongitude;
	}

	public void setMaxLongitude(String maxLongitude) {
		this.maxLongitude = maxLongitude;
	}

	public String getMaxLatitude() {
		return maxLatitude;
	}

	public void setMaxLatitude(String maxLatitude) {
		this.maxLatitude = maxLatitude;
	}

	public String getMinLongitude() {
		return minLongitude;
	}

	public void setMinLongitude(String minLongitude) {
		this.minLongitude = minLongitude;
	}

	public String getMinLatitude() {
		return minLatitude;
	}

	public void setMinLatitude(String minLatitude) {
		this.minLatitude = minLatitude;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getValid() {
		return valid;
	}

	public void setValid(String valid) {
		this.valid = valid;
	}

}
