package com.hgsoft.carowner.entity;

// Generated 2015-7-29 9:28:18 by Hibernate Tools 4.3.1

import java.util.Date;

import org.springframework.stereotype.Service;

/**
 * FaultCode generated by hbm2java
 */
public class FaultCode implements java.io.Serializable {

	private String faultId;
	private String code;
	private String cname;
	private Date createTime;
	private Character state;
	private String remark;

	public FaultCode() {
	}

	public FaultCode(String faultId) {
		this.faultId = faultId;
	}

	public FaultCode(String faultId, String code, String cname,
			Date createTime, Character state, String remark) {
		this.faultId = faultId;
		this.code = code;
		this.cname = cname;
		this.createTime = createTime;
		this.state = state;
		this.remark = remark;
	}

	public String getFaultId() {
		return this.faultId;
	}

	public void setFaultId(String faultId) {
		this.faultId = faultId;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Character getState() {
		return this.state;
	}

	public void setState(Character state) {
		this.state = state;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
