package com.hgsoft.carowner.entity;

// Generated 2015-8-7 14:44:29 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * FaultUpload generated by hbm2java
 */
public class FaultUpload implements java.io.Serializable {

	private String faultId;
	private String obdSn;
	private Integer faultTotal;
	private String faultCode;
	private Date createTime;
	private Date updateTime;
	private String state;
	private String remark;

	public FaultUpload() {
	}

	public FaultUpload(String faultId, String obdSn) {
		this.faultId = faultId;
		this.obdSn = obdSn;
	}

	public FaultUpload(String faultId, String obdSn, Integer faultTotal,
			String faultCode, Date createTime, Date updateTime,String state, String remark) {
		this.faultId = faultId;
		this.obdSn = obdSn;
		this.faultTotal = faultTotal;
		this.faultCode = faultCode;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.state = state;
		this.remark = remark;
	}

	public String getFaultId() {
		return this.faultId;
	}

	public void setFaultId(String faultId) {
		this.faultId = faultId;
	}

	public String getObdSn() {
		return this.obdSn;
	}

	public void setObdSn(String obdSn) {
		this.obdSn = obdSn;
	}

	public Integer getFaultTotal() {
		return this.faultTotal;
	}

	public void setFaultTotal(Integer faultTotal) {
		this.faultTotal = faultTotal;
	}

	public String getFaultCode() {
		return this.faultCode;
	}

	public void setFaultCode(String faultCode) {
		this.faultCode = faultCode;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Override
	public String toString() {
		return "FaultUpload [faultId=" + faultId + ", obdSn=" + obdSn
				+ ", faultTotal=" + faultTotal + ", faultCode=" + faultCode
				+ ", createTime=" + createTime + ", updateTime=" + updateTime
				+ ", state=" + state + ", remark=" + remark + "]";
	}
	
	

}
