package com.hgsoft.carowner.entity;
// Generated 2015-8-10 17:26:51 by Hibernate Tools 3.4.0.CR1

/**
 * MebCarFault generated by hbm2java
 */
public class MebCarFault implements java.io.Serializable {

	private String faultId;
	private String carId;
	private String obdSn;
	private String faultUpdateTime;
	private String speed;
	private String voltage;
	private String faultNum;
	private String faultType;
	private String temperature;
	private String jinqiYaLi;
	private String rotationalSpeed;
	private String dianHuoOneTiqianJiao;
	private String jinqiTemp;
	private String kongqiLiuliang;
	private String qijiemenWeizi;
	private String secKongqiZhuang;
	private String o2weizi;
	private String fadongJiStart;
	private String faultDriveNum;
	private String jgyouguiYali;
	private String dqyouguiYali;
	private String feiqiXunhuan;
	private String egrkaidu;
	private String zhengfaChongxi;
	private String ranyouYewei;
	private String zhengfaYali;
	private String daqiya;
	private String xiangduiQijiemen;
	private String huanjinTemp;
	private String youqimenB;
	private String youqimenC;
	private String jiasutaBanD;
	private String jiasutaBanE;
	private String jiasutaBanF;
	private String qijiemenKongziad;
	private String faultFadongjiRun;
	private String youguijueduiyaLic1;
	private String jiasutaBanFc2;
	private String jiyouTemp;
	private String dongjieFault;
	private String obdBefore;

	public MebCarFault() {
	}

	public MebCarFault(String faultId, String obdSn) {
		this.faultId = faultId;
		this.obdSn = obdSn;
	}

	public MebCarFault(String faultId, String carId, String obdSn,
			String faultUpdateTime, String speed, String voltage,
			String faultNum, String faultType, String temperature,
			String jinqiYaLi, String rotationalSpeed,
			String dianHuoOneTiqianJiao, String jinqiTemp,
			String kongqiLiuliang, String qijiemenWeizi,
			String secKongqiZhuang, String o2weizi, String fadongJiStart,
			String faultDriveNum, String jgyouguiYali, String dqyouguiYali,
			String feiqiXunhuan, String egrkaidu, String zhengfaChongxi,
			String ranyouYewei, String zhengfaYali, String daqiya,
			String xiangduiQijiemen, String huanjinTemp, String youqimenB,
			String youqimenC, String jiasutaBanD, String jiasutaBanE,
			String jiasutaBanF, String qijiemenKongziad,
			String faultFadongjiRun, String youguijueduiyaLic1,
			String jiasutaBanFc2, String jiyouTemp, String dongjieFault,
			String obdBefore) {
		this.faultId = faultId;
		this.carId = carId;
		this.obdSn = obdSn;
		this.faultUpdateTime = faultUpdateTime;
		this.speed = speed;
		this.voltage = voltage;
		this.faultNum = faultNum;
		this.faultType = faultType;
		this.temperature = temperature;
		this.jinqiYaLi = jinqiYaLi;
		this.rotationalSpeed = rotationalSpeed;
		this.dianHuoOneTiqianJiao = dianHuoOneTiqianJiao;
		this.jinqiTemp = jinqiTemp;
		this.kongqiLiuliang = kongqiLiuliang;
		this.qijiemenWeizi = qijiemenWeizi;
		this.secKongqiZhuang = secKongqiZhuang;
		this.o2weizi = o2weizi;
		this.fadongJiStart = fadongJiStart;
		this.faultDriveNum = faultDriveNum;
		this.jgyouguiYali = jgyouguiYali;
		this.dqyouguiYali = dqyouguiYali;
		this.feiqiXunhuan = feiqiXunhuan;
		this.egrkaidu = egrkaidu;
		this.zhengfaChongxi = zhengfaChongxi;
		this.ranyouYewei = ranyouYewei;
		this.zhengfaYali = zhengfaYali;
		this.daqiya = daqiya;
		this.xiangduiQijiemen = xiangduiQijiemen;
		this.huanjinTemp = huanjinTemp;
		this.youqimenB = youqimenB;
		this.youqimenC = youqimenC;
		this.jiasutaBanD = jiasutaBanD;
		this.jiasutaBanE = jiasutaBanE;
		this.jiasutaBanF = jiasutaBanF;
		this.qijiemenKongziad = qijiemenKongziad;
		this.faultFadongjiRun = faultFadongjiRun;
		this.youguijueduiyaLic1 = youguijueduiyaLic1;
		this.jiasutaBanFc2 = jiasutaBanFc2;
		this.jiyouTemp = jiyouTemp;
		this.dongjieFault = dongjieFault;
		this.obdBefore = obdBefore;
	}

	public String getFaultId() {
		return this.faultId;
	}

	public void setFaultId(String faultId) {
		this.faultId = faultId;
	}

	public String getCarId() {
		return this.carId;
	}

	public void setCarId(String carId) {
		this.carId = carId;
	}

	public String getObdSn() {
		return this.obdSn;
	}

	public void setObdSn(String obdSn) {
		this.obdSn = obdSn;
	}

	public String getFaultUpdateTime() {
		return this.faultUpdateTime;
	}

	public void setFaultUpdateTime(String faultUpdateTime) {
		this.faultUpdateTime = faultUpdateTime;
	}

	public String getSpeed() {
		return this.speed;
	}

	public void setSpeed(String speed) {
		this.speed = speed;
	}

	public String getVoltage() {
		return this.voltage;
	}

	public void setVoltage(String voltage) {
		this.voltage = voltage;
	}

	public String getFaultNum() {
		return this.faultNum;
	}

	public void setFaultNum(String faultNum) {
		this.faultNum = faultNum;
	}

	public String getFaultType() {
		return this.faultType;
	}

	public void setFaultType(String faultType) {
		this.faultType = faultType;
	}

	public String getTemperature() {
		return this.temperature;
	}

	public void setTemperature(String temperature) {
		this.temperature = temperature;
	}

	public String getJinqiYaLi() {
		return this.jinqiYaLi;
	}

	public void setJinqiYaLi(String jinqiYaLi) {
		this.jinqiYaLi = jinqiYaLi;
	}

	public String getRotationalSpeed() {
		return this.rotationalSpeed;
	}

	public void setRotationalSpeed(String rotationalSpeed) {
		this.rotationalSpeed = rotationalSpeed;
	}

	public String getDianHuoOneTiqianJiao() {
		return this.dianHuoOneTiqianJiao;
	}

	public void setDianHuoOneTiqianJiao(String dianHuoOneTiqianJiao) {
		this.dianHuoOneTiqianJiao = dianHuoOneTiqianJiao;
	}

	public String getJinqiTemp() {
		return this.jinqiTemp;
	}

	public void setJinqiTemp(String jinqiTemp) {
		this.jinqiTemp = jinqiTemp;
	}

	public String getKongqiLiuliang() {
		return this.kongqiLiuliang;
	}

	public void setKongqiLiuliang(String kongqiLiuliang) {
		this.kongqiLiuliang = kongqiLiuliang;
	}

	public String getQijiemenWeizi() {
		return this.qijiemenWeizi;
	}

	public void setQijiemenWeizi(String qijiemenWeizi) {
		this.qijiemenWeizi = qijiemenWeizi;
	}

	public String getSecKongqiZhuang() {
		return this.secKongqiZhuang;
	}

	public void setSecKongqiZhuang(String secKongqiZhuang) {
		this.secKongqiZhuang = secKongqiZhuang;
	}

	public String getO2weizi() {
		return this.o2weizi;
	}

	public void setO2weizi(String o2weizi) {
		this.o2weizi = o2weizi;
	}

	public String getFadongJiStart() {
		return this.fadongJiStart;
	}

	public void setFadongJiStart(String fadongJiStart) {
		this.fadongJiStart = fadongJiStart;
	}

	public String getFaultDriveNum() {
		return this.faultDriveNum;
	}

	public void setFaultDriveNum(String faultDriveNum) {
		this.faultDriveNum = faultDriveNum;
	}

	public String getJgyouguiYali() {
		return this.jgyouguiYali;
	}

	public void setJgyouguiYali(String jgyouguiYali) {
		this.jgyouguiYali = jgyouguiYali;
	}

	public String getDqyouguiYali() {
		return this.dqyouguiYali;
	}

	public void setDqyouguiYali(String dqyouguiYali) {
		this.dqyouguiYali = dqyouguiYali;
	}

	public String getFeiqiXunhuan() {
		return this.feiqiXunhuan;
	}

	public void setFeiqiXunhuan(String feiqiXunhuan) {
		this.feiqiXunhuan = feiqiXunhuan;
	}

	public String getEgrkaidu() {
		return this.egrkaidu;
	}

	public void setEgrkaidu(String egrkaidu) {
		this.egrkaidu = egrkaidu;
	}

	public String getZhengfaChongxi() {
		return this.zhengfaChongxi;
	}

	public void setZhengfaChongxi(String zhengfaChongxi) {
		this.zhengfaChongxi = zhengfaChongxi;
	}

	public String getRanyouYewei() {
		return this.ranyouYewei;
	}

	public void setRanyouYewei(String ranyouYewei) {
		this.ranyouYewei = ranyouYewei;
	}

	public String getZhengfaYali() {
		return this.zhengfaYali;
	}

	public void setZhengfaYali(String zhengfaYali) {
		this.zhengfaYali = zhengfaYali;
	}

	public String getDaqiya() {
		return this.daqiya;
	}

	public void setDaqiya(String daqiya) {
		this.daqiya = daqiya;
	}

	public String getXiangduiQijiemen() {
		return this.xiangduiQijiemen;
	}

	public void setXiangduiQijiemen(String xiangduiQijiemen) {
		this.xiangduiQijiemen = xiangduiQijiemen;
	}

	public String getHuanjinTemp() {
		return this.huanjinTemp;
	}

	public void setHuanjinTemp(String huanjinTemp) {
		this.huanjinTemp = huanjinTemp;
	}

	public String getYouqimenB() {
		return this.youqimenB;
	}

	public void setYouqimenB(String youqimenB) {
		this.youqimenB = youqimenB;
	}

	public String getYouqimenC() {
		return this.youqimenC;
	}

	public void setYouqimenC(String youqimenC) {
		this.youqimenC = youqimenC;
	}

	public String getJiasutaBanD() {
		return this.jiasutaBanD;
	}

	public void setJiasutaBanD(String jiasutaBanD) {
		this.jiasutaBanD = jiasutaBanD;
	}

	public String getJiasutaBanE() {
		return this.jiasutaBanE;
	}

	public void setJiasutaBanE(String jiasutaBanE) {
		this.jiasutaBanE = jiasutaBanE;
	}

	public String getJiasutaBanF() {
		return this.jiasutaBanF;
	}

	public void setJiasutaBanF(String jiasutaBanF) {
		this.jiasutaBanF = jiasutaBanF;
	}

	public String getQijiemenKongziad() {
		return this.qijiemenKongziad;
	}

	public void setQijiemenKongziad(String qijiemenKongziad) {
		this.qijiemenKongziad = qijiemenKongziad;
	}

	public String getFaultFadongjiRun() {
		return this.faultFadongjiRun;
	}

	public void setFaultFadongjiRun(String faultFadongjiRun) {
		this.faultFadongjiRun = faultFadongjiRun;
	}

	public String getYouguijueduiyaLic1() {
		return this.youguijueduiyaLic1;
	}

	public void setYouguijueduiyaLic1(String youguijueduiyaLic1) {
		this.youguijueduiyaLic1 = youguijueduiyaLic1;
	}

	public String getJiasutaBanFc2() {
		return this.jiasutaBanFc2;
	}

	public void setJiasutaBanFc2(String jiasutaBanFc2) {
		this.jiasutaBanFc2 = jiasutaBanFc2;
	}

	public String getJiyouTemp() {
		return this.jiyouTemp;
	}

	public void setJiyouTemp(String jiyouTemp) {
		this.jiyouTemp = jiyouTemp;
	}

	public String getDongjieFault() {
		return this.dongjieFault;
	}

	public void setDongjieFault(String dongjieFault) {
		this.dongjieFault = dongjieFault;
	}

	public String getObdBefore() {
		return this.obdBefore;
	}

	public void setObdBefore(String obdBefore) {
		this.obdBefore = obdBefore;
	}

}
