package com.hgsoft.carowner.entity;

import java.util.Date;

// Generated 2015-7-29 17:16:29 by Hibernate Tools 3.4.0.CR1

/**
 * MebUser generated by hbm2java
 */
public class MebUser implements java.io.Serializable {

	private String regUserId;
	private String mobileNumber;
	private String obdSN;
	private String carId;
	private String license;
	private String name;
	private String sex;
	private Integer userType;//用户类型	1 华工	2 车主通
	private String password;
	private String payPassword;
	private Date createTime;
	private Date updateTime;
	private String valid;
	//虚拟字段
	private String city;
	private String letter;
	private String number;

	public MebUser() {
	}

	public MebUser(String regUserId) {
		this.regUserId = regUserId;
	}

	public MebUser(String regUserId, String mobileNumber, String obdSN,String carId,
			String license, String name, String sex,
			Integer userType, String password, String payPassword, String valid) {
		this.regUserId = regUserId;
		this.mobileNumber = mobileNumber;
		this.obdSN = obdSN;
		this.carId = carId;
		this.license = license;
		this.name = name;
		this.sex = sex;
		this.userType = userType;
		this.password = password;
		this.payPassword = payPassword;
		this.valid = valid;
	}

	public String getRegUserId() {
		return this.regUserId;
	}

	public void setRegUserId(String regUserId) {
		this.regUserId = regUserId;
	}

	public String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	public String getObdSN() {
		return this.obdSN;
	}

	public void setObdSN(String obdSN) {
		this.obdSN = obdSN;
	}

	public String getLicense() {
		return this.license;
	}

	public void setLicense(String license) {
		this.license = license;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Integer getUserType() {
		return this.userType;
	}

	public void setUserType(Integer userType) {
		this.userType = userType;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPayPassword() {
		return this.payPassword;
	}

	public void setPayPassword(String payPassword) {
		this.payPassword = payPassword;
	}

	public String getValid() {
		return this.valid;
	}

	public void setValid(String valid) {
		this.valid = valid;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getLetter() {
		return letter;
	}

	public void setLetter(String letter) {
		this.letter = letter;
	}

	public String getNumber() {
		return number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getCarId() {
		return carId;
	}

	public void setCarId(String carId) {
		this.carId = carId;
	}
	
}
