package com.hgsoft.carowner.entity;


import java.util.Date;

/**
 * Wifi generated by hbm2java
 */
public class ObdBatchSet implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	private String obdSn;
	private String type;
	private String version;
	private Date createTime;
	private Date updateTime;
	private Integer valid;//是否有效
	private String auditOper;
	private Date auditTime;
	private Integer auditState;
	private Integer sendedCount;
	private Integer success;
	
	public ObdBatchSet() {
	}


	public String getObdSn() {
		return obdSn;
	}

	public void setObdSn(String obdSn) {
		this.obdSn = obdSn;
	}

	public String getVersion() {
		return version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}


	public static long getSerialversionuid() {
		return serialVersionUID;
	}


	public String getAuditOper() {
		return auditOper;
	}

	public void setAuditOper(String auditOper) {
		this.auditOper = auditOper;
	}

	public Date getAuditTime() {
		return auditTime;
	}

	public void setAuditTime(Date auditTime) {
		this.auditTime = auditTime;
	}


	public Integer getAuditState() {
		return auditState;
	}


	public void setAuditState(Integer auditState) {
		this.auditState = auditState;
	}


	public String getId() {
		return id;
	}


	public void setId(String id) {
		this.id = id;
	}


	public String getType() {
		return type;
	}


	public void setType(String type) {
		this.type = type;
	}


	public Integer getValid() {
		return valid;
	}


	public void setValid(Integer valid) {
		this.valid = valid;
	}


	public Integer getSendedCount() {
		return sendedCount;
	}


	public void setSendedCount(Integer sendedCount) {
		this.sendedCount = sendedCount;
	}


	public Integer getSuccess() {
		return success;
	}


	public void setSuccess(Integer success) {
		this.success = success;
	}


	@Override
	public String toString() {
		return "obdBatchSet [id=" + id + ", obdSn=" + obdSn + ", type=" + type + ", version=" + version
				+ ", createTime=" + createTime + ", updateTime=" + updateTime + ", valid=" + valid + ", auditOper="
				+ auditOper + ", auditTime=" + auditTime + ", auditState=" + auditState + ", sendedCount=" + sendedCount
				+ ", success=" + success + "]";
	}


}
