package com.hgsoft.carowner.entity;

// Generated 2015-7-31 9:07:01 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * ObdIp generated by hbm2java
 */
public class ObdIp implements java.io.Serializable {

	private String obdIpId;
	private String ip;
	private Integer port;
	private String obdId;
	private Date createTime;
	private Character state;
	private String remark;

	public ObdIp() {
	}

	public ObdIp(String obdIpId) {
		this.obdIpId = obdIpId;
	}

	public ObdIp(String obdIpId, String ip, Integer port, String obdId,
			Date createTime, Character state, String remark) {
		this.obdIpId = obdIpId;
		this.ip = ip;
		this.port = port;
		this.obdId = obdId;
		this.createTime = createTime;
		this.state = state;
		this.remark = remark;
	}

	public String getObdIpId() {
		return this.obdIpId;
	}

	public void setObdIpId(String obdIpId) {
		this.obdIpId = obdIpId;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public Integer getPort() {
		return this.port;
	}

	public void setPort(Integer port) {
		this.port = port;
	}

	public String getObdId() {
		return this.obdId;
	}

	public void setObdId(String obdId) {
		this.obdId = obdId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Character getState() {
		return this.state;
	}

	public void setState(Character state) {
		this.state = state;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
