package com.hgsoft.carowner.entity;


import java.util.Date;

/**
 * Wifi generated by hbm2java
 */
public class ObdState implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	private String obdSn;
	private String startupSwitch;//非法启动预警开关
	private String shakeSwitch;//车辆震动报警开关，0关闭，1打开
	private String voltageSwitch;//蓄电电压异常报警开关
	private String engineTempSwitch;//发动机水温高报警开关
	private String carfaultSwitch;//车辆故障报警
	private String overspeedSwitch;//超速报警开关
	private String efenceSwitch;//电子围栏报警
	private String backupSwitch;//保留开关
	private String wifiState;//wifi开关状态
	private String gpsState;//gps状态
	private String safetySwitch;//设防撤防开关,0关闭，1打开
	private String rapidSpeedChangeSwitch;//急变速预警开关,0关闭，1打开
	private String idlingSwitch;//怠速预警开关,0关闭，1打开
	private String fatigueDriveSwitch;//疲劳驾驶预警推送开关,0关闭，1打开
	private String wakeup;//设备自动唤醒开关,0关闭，1打开
	private Date createTime;
	private Date updateTime;
	private String valid;

	public ObdState() {
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getObdSn() {
		return obdSn;
	}

	public void setObdSn(String obdSn) {
		this.obdSn = obdSn;
	}

	public String getStartupSwitch() {
		return startupSwitch;
	}

	public void setStartupSwitch(String startupSwitch) {
		this.startupSwitch = startupSwitch;
	}

	public String getShakeSwitch() {
		return shakeSwitch;
	}

	public void setShakeSwitch(String shakeSwitch) {
		this.shakeSwitch = shakeSwitch;
	}

	public String getVoltageSwitch() {
		return voltageSwitch;
	}

	public void setVoltageSwitch(String voltageSwitch) {
		this.voltageSwitch = voltageSwitch;
	}

	public String getEngineTempSwitch() {
		return engineTempSwitch;
	}

	public void setEngineTempSwitch(String engineTempSwitch) {
		this.engineTempSwitch = engineTempSwitch;
	}

	public String getCarfaultSwitch() {
		return carfaultSwitch;
	}

	public void setCarfaultSwitch(String carfaultSwitch) {
		this.carfaultSwitch = carfaultSwitch;
	}

	public String getOverspeedSwitch() {
		return overspeedSwitch;
	}

	public void setOverspeedSwitch(String overspeedSwitch) {
		this.overspeedSwitch = overspeedSwitch;
	}

	public String getEfenceSwitch() {
		return efenceSwitch;
	}

	public void setEfenceSwitch(String efenceSwitch) {
		this.efenceSwitch = efenceSwitch;
	}

	public String getBackupSwitch() {
		return backupSwitch;
	}

	public void setBackupSwitch(String backupSwitch) {
		this.backupSwitch = backupSwitch;
	}

	public String getWifiState() {
		return wifiState;
	}

	public void setWifiState(String wifiState) {
		this.wifiState = wifiState;
	}

	public String getGpsState() {
		return gpsState;
	}

	public void setGpsState(String gpsState) {
		this.gpsState = gpsState;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getValid() {
		return valid;
	}

	public void setValid(String valid) {
		this.valid = valid;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public String getSafetySwitch() {
		return safetySwitch;
	}

	public void setSafetySwitch(String safetySwitch) {
		this.safetySwitch = safetySwitch;
	}
	
	public String getRapidSpeedChangeSwitch() {
		return rapidSpeedChangeSwitch;
	}

	public void setRapidSpeedChangeSwitch(String rapidSpeedChangeSwitch) {
		this.rapidSpeedChangeSwitch = rapidSpeedChangeSwitch;
	}

	public String getIdlingSwitch() {
		return idlingSwitch;
	}

	public void setIdlingSwitch(String idlingSwitch) {
		this.idlingSwitch = idlingSwitch;
	}

	public String getFatigueDriveSwitch() {
		return fatigueDriveSwitch;
	}

	public void setFatigueDriveSwitch(String fatigueDriveSwitch) {
		this.fatigueDriveSwitch = fatigueDriveSwitch;
	}

	public String getWakeup() {
		return wakeup;
	}

	public void setWakeup(String wakeup) {
		this.wakeup = wakeup;
	}

	@Override
	public String toString() {
		return "ObdState [id=" + id + ", obdSn=" + obdSn + ", startupSwitch=" + startupSwitch + ", shakeSwitch="
				+ shakeSwitch + ", voltageSwitch=" + voltageSwitch + ", engineTempSwitch=" + engineTempSwitch
				+ ", carfaultSwitch=" + carfaultSwitch + ", overspeedSwitch=" + overspeedSwitch + ", efenceSwitch="
				+ efenceSwitch + ", backupSwitch=" + backupSwitch + ", wifiState=" + wifiState + ", gpsState="
				+ gpsState + ", safetySwitch=" + safetySwitch + ", rapidSpeedChangeSwitch=" + rapidSpeedChangeSwitch
				+ ", idlingSwitch=" + idlingSwitch + ", fatigueDriveSwitch=" + fatigueDriveSwitch + ", wakeup=" + wakeup
				+ ", createTime=" + createTime + ", updateTime=" + updateTime + ", valid=" + valid + "]";
	}

}
