package com.hgsoft.carowner.entity;


import java.util.Date;

/**
 * ObdVersion generated by hbm2java
 */
public class ObdVersion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String obdSn;
	private String version;
	private String firmVersion;
	private Integer firmType;
	private String updateFlag;
	private Date createTime;
	private Date updateTime;
	private String remark;

	public ObdVersion() {
	}

//	public ObdVersion(String obdSn, String version, String updateFlag,
//			String noticeVersion,String notice,Date noticeTime, 
//			Date createTime, Date updateTime, String remark) {
//		this.obdSn = obdSn;
//		this.version = version;
//		this.updateFlag = updateFlag;
//		this.createTime = createTime;
//		this.updateTime = updateTime;
//		this.remark = remark;
//	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getObdSn() {
		return obdSn;
	}

	public void setObdSn(String obdSn) {
		this.obdSn = obdSn;
	}

	public String getVersion() {
		return version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public String getUpdateFlag() {
		return updateFlag;
	}

	public void setUpdateFlag(String updateFlag) {
		this.updateFlag = updateFlag;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getFirmVersion() {
		return firmVersion;
	}

	public void setFirmVersion(String firmVersion) {
		this.firmVersion = firmVersion;
	}

	public Integer getFirmType() {
		return firmType;
	}

	public void setFirmType(Integer firmType) {
		this.firmType = firmType;
	}

}
