package com.hgsoft.carowner.entity;

import java.util.Date;

/**
 * ObdVersion generated by hbm2java
 */
public class Portal implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String obdSn;
	private String type;//操作类型
	private String url;//设置url
	private String mb;//流量额度限制
	private String whitelists;//白名单限制
	private String mac;//手机mac地址
	private String onOff;//PROTAL开关.0关闭，1打开
	private Date createTime;
	private Date updateTime;
	private String valid;//是否有效0无效1有效

	public Portal() {
	}

		
	
	@Override
	public String toString() {
		return "Portal [id=" + id + ", obdSn=" + obdSn + ", type=" + type + ", url=" + url + ", mb=" + mb
				+ ", whitelists=" + whitelists + ", mac=" + mac + ", onOff=" + onOff + ", createTime=" + createTime
				+ ", updateTime=" + updateTime + ", valid=" + valid + "]";
	}



	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getMb() {
		return mb;
	}

	public void setMb(String mb) {
		this.mb = mb;
	}

	public String getWhitelists() {
		return whitelists;
	}

	public void setWhitelists(String whitelists) {
		this.whitelists = whitelists;
	}

	public String getObdSn() {
		return obdSn;
	}

	public void setObdSn(String obdSn) {
		this.obdSn = obdSn;
	}

	public String getMac() {
		return mac;
	}

	public void setMac(String mac) {
		this.mac = mac;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getValid() {
		return valid;
	}

	public void setValid(String valid) {
		this.valid = valid;
	}

	public String getOnOff() {
		return onOff;
	}

	public void setOnOff(String onOff) {
		this.onOff = onOff;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	
}
