package com.hgsoft.carowner.entity;
// Generated 2015-8-4 15:02:56 by Hibernate Tools 3.4.0.CR1

/**
 * SerInformationman generated by hbm2java
 */
public class SerInformationman implements java.io.Serializable {

	private Integer infoId;
	private String infoType;
	private String infoTitle;
	private String summary;
	private String infoDetail;
	private String infoTime;
	private String infoShow;
	private String infoRedShow;
	private String regUserId;

	public SerInformationman() {
	}

	public SerInformationman(String infoType, String infoTitle, String summary,
			String infoDetail, String infoTime, String infoShow,
			String infoRedShow,String regUserId) {
		this.infoType = infoType;
		this.infoTitle = infoTitle;
		this.summary = summary;
		this.infoDetail = infoDetail;
		this.infoTime = infoTime;
		this.infoShow = infoShow;
		this.infoRedShow = infoRedShow;
		this.regUserId=regUserId;
	}

	public Integer getInfoId() {
		return this.infoId;
	}

	public void setInfoId(Integer infoId) {
		this.infoId = infoId;
	}

	public String getInfoType() {
		return this.infoType;
	}

	public void setInfoType(String infoType) {
		this.infoType = infoType;
	}

	public String getInfoTitle() {
		return this.infoTitle;
	}

	public void setInfoTitle(String infoTitle) {
		this.infoTitle = infoTitle;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public String getInfoDetail() {
		return this.infoDetail;
	}

	public void setInfoDetail(String infoDetail) {
		this.infoDetail = infoDetail;
	}

	public String getInfoTime() {
		return this.infoTime;
	}

	public void setInfoTime(String infoTime) {
		this.infoTime = infoTime;
	}

	public String getInfoShow() {
		return this.infoShow;
	}

	public void setInfoShow(String infoShow) {
		this.infoShow = infoShow;
	}

	public String getInfoRedShow() {
		return this.infoRedShow;
	}

	public void setInfoRedShow(String infoRedShow) {
		this.infoRedShow = infoRedShow;
	}

	public String getRegUserId() {
		return regUserId;
	}

	public void setRegUserId(String regUserId) {
		this.regUserId = regUserId;
	}
	
	
}
