package com.hgsoft.carowner.entity;
// Generated 2015-8-14 11:55:48 by Hibernate Tools 3.4.0.CR1

/**
 * SerMessageinfo generated by hbm2java
 */
public class SerMessageinfo implements java.io.Serializable {

	private String messageId;
	private String messageType;
	private String messageRec;
	private String messageText;
	private String messageTime;

	public SerMessageinfo() {
	}

	public SerMessageinfo(String messageId) {
		this.messageId = messageId;
	}

	public SerMessageinfo(String messageId, String messageType,
			String messageRec, String messageText, String messageTime) {
		this.messageId = messageId;
		this.messageType = messageType;
		this.messageRec = messageRec;
		this.messageText = messageText;
		this.messageTime = messageTime;
	}

	public String getMessageId() {
		return this.messageId;
	}

	public void setMessageId(String messageId) {
		this.messageId = messageId;
	}

	public String getMessageType() {
		return this.messageType;
	}

	public void setMessageType(String messageType) {
		this.messageType = messageType;
	}

	public String getMessageRec() {
		return this.messageRec;
	}

	public void setMessageRec(String messageRec) {
		this.messageRec = messageRec;
	}

	public String getMessageText() {
		return this.messageText;
	}

	public void setMessageText(String messageText) {
		this.messageText = messageText;
	}

	public String getMessageTime() {
		return this.messageTime;
	}

	public void setMessageTime(String messageTime) {
		this.messageTime = messageTime;
	}

}
