package com.hgsoft.carowner.entity;


import java.util.Date;

/**
 * Wifi generated by hbm2java
 */
public class WifiSet implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String obdSn;
	private String type;//设置类别1：修改SSID ；2：修改WIFI密码3：WIFI出厂设置 4:wifi开关设置
	private String ssid;//车辆ssid号
	private String autu;//WIFI共享方式
	private String encrypt;//Wifi密码加密方式
	private String wifiPwd;//wifi密码
	private String wifiState;//wifi开关设置，1打开，0关闭
	private Integer useTime;
	private Date createTime;
	private Date updateTime;
	private String valid;//是否有效0无效1有效

	public WifiSet() {
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getObdSn() {
		return obdSn;
	}

	public void setObdSn(String obdSn) {
		this.obdSn = obdSn;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getSsid() {
		return ssid;
	}

	public void setSsid(String ssid) {
		this.ssid = ssid;
	}

	public String getAutu() {
		return autu;
	}

	public void setAutu(String autu) {
		this.autu = autu;
	}

	public String getEncrypt() {
		return encrypt;
	}

	public void setEncrypt(String encrypt) {
		this.encrypt = encrypt;
	}

	public String getWifiPwd() {
		return wifiPwd;
	}

	public void setWifiPwd(String wifiPwd) {
		this.wifiPwd = wifiPwd;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getValid() {
		return valid;
	}

	public void setValid(String valid) {
		this.valid = valid;
	}

	public String getWifiState() {
		return wifiState;
	}

	public void setWifiState(String wifiState) {
		this.wifiState = wifiState;
	}

	public Integer getUseTime() {
		return useTime;
	}

	public void setUseTime(Integer useTime) {
		this.useTime = useTime;
	}

	@Override
	public String toString() {
		return "WifiSet [id=" + id + ", obdSn=" + obdSn + ", type=" + type
				+ ", ssid=" + ssid + ", autu=" + autu + ", encrypt=" + encrypt
				+ ", wifiPwd=" + wifiPwd + ", wifiState=" + wifiState
				+ ", useTime=" + useTime + ", createTime=" + createTime
				+ ", updateTime=" + updateTime + ", valid=" + valid + "]";
	}

	

	
}
